"""Core types for the Model Gateway.

All types are frozen dataclasses (immutable) so routing decisions and usage
records are tamper-evident after creation.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum


class TaskKind(StrEnum):
    """Categorises what an LLM call is being used for."""

    LITERATURE_SEARCH = "literature_search"
    SCREENING = "screening"
    FIRST_PASS_EXTRACTION = "first_pass_extraction"
    EVIDENCE_AUDIT = "evidence_audit"
    CITATION_AUDIT = "citation_audit"
    SECTION_WRITING = "section_writing"
    METHODOLOGY_CRITIC = "methodology_critic"
    STATISTICS_CRITIC = "statistics_critic"
    REVIEWER = "reviewer"
    FINAL_COMPLIANCE_AUDIT = "final_compliance_audit"
    FORMAT_CONVERSION = "format_conversion"
    SCHEMA_REPAIR = "schema_repair"


class ModelTier(StrEnum):
    """Coarse capability/price band for models."""

    CHEAP_BATCH = "cheap_batch"
    BALANCED_WRITE = "balanced_write"
    HIGH_REASONING = "high_reasoning"


# Default mapping: task kind → tier + minimum risk threshold for upgrade.
_TASK_TIER_MAP: dict[TaskKind, ModelTier] = {
    TaskKind.LITERATURE_SEARCH: ModelTier.CHEAP_BATCH,
    TaskKind.SCREENING: ModelTier.CHEAP_BATCH,
    TaskKind.FIRST_PASS_EXTRACTION: ModelTier.CHEAP_BATCH,
    TaskKind.FORMAT_CONVERSION: ModelTier.CHEAP_BATCH,
    TaskKind.SCHEMA_REPAIR: ModelTier.CHEAP_BATCH,
    TaskKind.EVIDENCE_AUDIT: ModelTier.BALANCED_WRITE,
    TaskKind.CITATION_AUDIT: ModelTier.BALANCED_WRITE,
    TaskKind.SECTION_WRITING: ModelTier.BALANCED_WRITE,
    TaskKind.METHODOLOGY_CRITIC: ModelTier.HIGH_REASONING,
    TaskKind.STATISTICS_CRITIC: ModelTier.HIGH_REASONING,
    TaskKind.REVIEWER: ModelTier.HIGH_REASONING,
    TaskKind.FINAL_COMPLIANCE_AUDIT: ModelTier.HIGH_REASONING,
}


def default_tier_for_task(task: TaskKind) -> ModelTier:
    """Return the default model tier for a given task kind."""

    return _TASK_TIER_MAP.get(task, ModelTier.BALANCED_WRITE)


@dataclass(frozen=True, slots=True)
class ModelProfile:
    """Static capability/metadata for a model variant.

    ``context_window`` and ``max_output_tokens`` are in token units.
    ``capabilities`` is a set of string tags (e.g. ``"json_mode"``,
    ``"vision"``, ``"tool_use"``).
    """

    model_id: str
    provider: str
    tier: ModelTier
    context_window: int
    max_output_tokens: int
    capabilities: frozenset[str] = field(default_factory=frozenset)


@dataclass(frozen=True, slots=True)
class BudgetLimit:
    """Hard cost ceiling expressed in USD cents.

    ``spent_cents`` is the running total so far.  When
    ``spent_cents + estimated_cost_cents > limit_cents`` the router
    must signal budget exhaustion instead of silently downgrading.
    """

    scope: str  # "project", "run", "stage"
    limit_cents: int
    spent_cents: int = 0

    @property
    def remaining_cents(self) -> int:
        return max(0, self.limit_cents - self.spent_cents)

    @property
    def is_exhausted(self) -> bool:
        return self.spent_cents >= self.limit_cents


@dataclass(frozen=True, slots=True)
class AgentTaskSpec:
    """Input to the Router: what the calling node wants to do.

    ``estimated_input_tokens`` is a rough token count (approx 4 chars/token).
    ``estimated_output_tokens`` is the expected output size.
    ``required_capabilities`` lets the caller assert e.g. ``"json_mode"``.
    ``risk_level`` ranges from 0 (lowest) to 3 (highest).  High-risk tasks
    are auto-upgraded to ``high_reasoning``.
    """

    task_kind: TaskKind
    estimated_input_tokens: int
    estimated_output_tokens: int
    required_capabilities: frozenset[str] = field(default_factory=frozenset)
    risk_level: int = 0
    fallback_order: tuple[str, ...] = ()
    project_id: str = ""
    run_id: str = ""
    stage: str = ""


@dataclass(frozen=True, slots=True)
class RoutingDecision:
    """Output of the Router: which model to use and why.

    ``rationale`` is a short human-readable explanation generated by the
    deterministic policy (not by an LLM).  ``budget_ok`` is False when
    the estimated cost exceeds the remaining budget; callers must treat
    this as a hard stop and request human approval.
    """

    model_id: str
    provider: str
    tier: ModelTier
    rationale: str
    estimated_cost_cents: int
    budget_ok: bool
    fallback_chain: tuple[str, ...] = ()


@dataclass(frozen=True, slots=True)
class TokenUsageRecord:
    """Token counts and cost for a single model invocation."""

    model_id: str
    provider: str
    input_tokens: int
    output_tokens: int
    cached_input_tokens: int = 0
    cost_cents: int = 0
    cache_hit: bool = False

    @property
    def total_tokens(self) -> int:
        return self.input_tokens + self.output_tokens


@dataclass(frozen=True, slots=True)
class ModelInvocation:
    """Full provenance record for one model call.

    Binds the routing decision, usage, and status so the ``AI_USAGE_LOG``
    artifact can be reconstructed deterministically.
    """

    invocation_id: str
    task_kind: TaskKind
    model_id: str
    provider: str
    tier: ModelTier
    prompt_template_version: str
    input_hash: str
    routing_decision: RoutingDecision
    usage: TokenUsageRecord
    status: str  # "success", "fallback", "failed"
    fallback_from: str | None = None
    error_message: str | None = None
    timestamp: str = ""


@dataclass(frozen=True, slots=True)
class UsageLog:
    """Aggregated AI usage log for artifact persistence.

    Maps directly to the ``AI_USAGE_LOG`` artifact type.
    """

    invocations: list[ModelInvocation] = field(default_factory=list)

    @property
    def total_cost_cents(self) -> int:
        return sum(inv.usage.cost_cents for inv in self.invocations)

    @property
    def total_input_tokens(self) -> int:
        return sum(inv.usage.input_tokens for inv in self.invocations)

    @property
    def total_output_tokens(self) -> int:
        return sum(inv.usage.output_tokens for inv in self.invocations)

    @property
    def fallback_count(self) -> int:
        return sum(1 for inv in self.invocations if inv.status == "fallback")

    @property
    def failure_count(self) -> int:
        return sum(1 for inv in self.invocations if inv.status == "failed")

    def to_dict(self) -> dict[str, object]:
        """Serialise to a JSON-safe dict for artifact payload."""

        return {
            "total_invocations": len(self.invocations),
            "total_cost_cents": self.total_cost_cents,
            "total_input_tokens": self.total_input_tokens,
            "total_output_tokens": self.total_output_tokens,
            "fallback_count": self.fallback_count,
            "failure_count": self.failure_count,
            "invocations": [
                {
                    "invocation_id": inv.invocation_id,
                    "task_kind": inv.task_kind.value,
                    "model_id": inv.model_id,
                    "provider": inv.provider,
                    "tier": inv.tier.value,
                    "status": inv.status,
                    "cost_cents": inv.usage.cost_cents,
                    "input_tokens": inv.usage.input_tokens,
                    "output_tokens": inv.usage.output_tokens,
                    "fallback_from": inv.fallback_from,
                }
                for inv in self.invocations
            ],
        }
